### ISSUE TITLE
Upsert() - throw an exception on badly formed SQL

### ISSUE THREAD

**Issue by greggjc** [ronglasmann/LiteSQLite#1]
Upsert appears to generate an "insert or ignore" sql command.  If the sql string is bad (for example, passing a null for a non-null column) the Upsert does what was asked...it ignores this...but it would be helpful in debugging if the only "ignore" was due to the fact that the record already existed for the  specified key.

**Comment by ronglasmann** [comment]
This shouldn't be an issue in v1.1.3
